### ISSUE TITLE
"Aufräumarbeiten"

### ISSUE THREAD

**Issue by ratnaweera** [ratnanil/Songs#32]
Danke für die Einladung Song-Projekt! Finde ich eine super Sache.

Ein paar Punkte, die mir als "Einsteiger" auffallen, die man allenfalls aufräumen könnte:

- [x] top level Ordner: Sind die alle nötig? (bsp "notes_and_tabs", "song_md1", "song_md2" etc.)
- [x] top level Dateien: Werden die "_*.xxx" Dateien benutzt oder müssten die allenfalls in ein .gitignore rein?
- [x] für das README.md: Kurzanleitung zum neu kompilieren für den HTML und PDF output?

**Comment by ratnanil** [comment]
>  top level Ordner: Sind die alle nötig? (bsp "notes_and_tabs", "song_md1", "song_md2" etc.)

hab da etwas aufgeräumt

>  top level Dateien: Werden die "_*.xxx" Dateien benutzt oder müssten die allenfalls in ein .gitignore rein?

die _*.yaml files braucht es 

>  für das README.md: Kurzanleitung zum neu kompilieren für den HTML und PDF output?

erledigt (https://github.com/ratnanil/Songs/commit/16396d931cc7f58201bccba9cf3232a60ca06ac5)

**Comment by ratnanil** [comment]
aufräumen wird wohl nie aufhören, aber die wichtigsten sachen sind vorerst gemacht. ich schliesse diesen issue
